server:
  port: 8188

  servlet:
    context-path: /test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qrup28
    username: root
    password: AyAn123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none