server:
  port: 8181
  servlet:
    context-path: /test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qrup28
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml