server:
  port: 8181
  servlet:
    context-path: /qrup28

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/qrup28
    username: root
    password: Alishov636590
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

fakeApi:
  url: https://jsonplaceholder.typicode.com
